version: '3.8'

services:

  students-management-service:
    build:
      context: .
      dockerfile: src/Microservices/StudentsManagementService/NinjaJournal.StudentsManagement.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - ConnectionStrings__StudentsManagementDbContext=Host=students-management-db;Database=students-management-db;Username=students-management-db;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - elasticsearch
      - students-management-db
    networks:
      - elastic

  students-management-db:
    container_name: students-management-db
    image: postgres:12
    environment:
      - POSTGRES_USER=students-management-db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students-management-db
    ports:
      - "5432:5432"
    volumes:
      - students-management-db-data:/usr/share/postgresql/data
    networks:
      - elastic

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic
  
  kibana:
    container_name: kibana
    image: kibana:8.7.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch 
      - students-management-service
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data: {}
  students-management-db-data: {} 